# This file can be used to install module dependencies for unit testing.
# Run `regent fixtures` to download the modules declared here into
# spec/fixtures/modules. See https://github.com/felipe-quintella/regent
---
fixtures:
  forge_modules:
     stdlib: "puppetlabs/stdlib"
     docker: "puppetlabs/docker"
     apt: "puppetlabs/apt"
     dockerapp: "ffquintella/dockerapp"

